### ISSUE TITLE
Carbon Absorption Values

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#48] opened 2012-06-14 11:51 UTC
We're testing carbon absorption and we're unable to invest enough money to perform any improvement in whole units of carbon.

Something to look into.

**Comment by piotroslaw** [comment] 2012-06-14 12:02
What exactly seems to be an issue? I have merged my and Nik's version manually yesterday after testing, so there might be some small mistake somewhere

**Comment by tumblerer** [comment] 2012-06-14 12:12
Whatever amount you try to invest, it claims you do not have enough money.

**Comment by piotroslaw** [comment] 2012-06-14 12:22
are you sure you do actually have enough money? the constants (CARBON_ABSORPTION_MIN and CARBON_ABSORPTION_MAX) are set to some random values. try setting them very low, and see if the problem persists.

I have just run my test agent on Testing branch with low constants (1 & 5), and all went well.

**Comment by tumblerer** [comment] 2012-06-14 13:09
Being looked into.

**Comment by n1kunj** [comment] 2012-06-14 13:38
I haven't tried investing anything but I've tested all the other functions in the reduction/absorption handlers and they seem to be working exactly as expected.

There was a nasty bug in the reduction handler with a flipped sign but I fixed that last night, and just now confirmed that it still is fixed.

**Comment by piotroslaw** [comment] 2012-06-14 14:15
Solved.

**Closed as completed by piotroslaw** 2012-06-14 14:15 UTC
Labels: bug
