### ISSUE TITLE
Carbon Absorption using Carbon Output

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#52] opened 2012-06-14 21:05 UTC
Line 105 of the carbon absorption handler refers to carbonOutput when calling getCarbonAbsorptionChange.

I couldn't work out why this would be, since carbonAbsoprtion and carbonOutput are different things.  

This is more a case of drawing attention to it.  If its correct, just say so and close this.

**Comment by piotroslaw** [comment] 2012-06-14 22:07
I have noticed it today as well.

The way that function works, is it uses binary search to find the carbon Absorption increase matching given investment. The problem is, carbonAbsorption is potentially unbounded (can be as high as country wants), and binary search requires lower and upper bound.

As far as I understand, the idea here is that it would be silly for a country to invest in carbon absorption that is higher than carbon output. Hence, the function assumes that the higher bound of carbon absorption increase is the carbon output, while lower is obviously 0. This means that the highest value that function will return will tend to current carbon output.

I'm not sure that this is the actual idea - Nikunj wrote this function. But if I'm correct, then carbonDiff should be initialised to (carbonOutput - carbonAbsorption), so that the upper bound (the maximum that can be returned) would actually force resulting emissions to 0.

We can talk about it tomorrow.

**Comment by piotroslaw** [comment] 2012-06-15 11:33
done, closing

**Closed as completed by piotroslaw** 2012-06-15 11:33 UTC
Labels: question
